### ISSUE TITLE
How to create UML for test files

### ISSUE THREAD

**Issue by yaohongkok** [juanmf/Java2PlantUML#11]
I am trying to use this project to create the UML diagrams for test codes. Is there some way I can do that?

If not, this could be a very useful feature to add.

**Comment by juanmf** [comment]
It works on anything loaded in class path. so you could run it from a unit Test. but you'll have production code as well in the outputs. Not sure how to separate given their packages match. Should look into src vs tst directories if possible...
Sorry for the late response. Not actively maintaining this now.

**Comment by juanmf** [comment]
see https://github.com/juanmf/Java2PlantUML/blob/master/src/main/java/com/github/juanmf/java2plant/Main.java#L27
for a programatic approach you can use from a unit test.

**Comment by yaohongkok** [comment]
It is all good. Thanks for the reply nonetheless!

Yao
