### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by gbonnefille** [juanmf/Java2PlantUML#5]
Can you add a license information both in a LICENSE and in source files?

Currently, your tool is reasonably unusable.

**Comment by juanmf** [comment]
ups, sure, I'll add it.

**Comment by juanmf** [comment]
https://github.com/juanmf/Java2PlantUML/blob/master/License.txt

**Comment by juanmf** [comment]
source changes pending

**Comment by gbonnefille** [comment]
Thanks.

**Comment by juanmf** [comment]
Done adding Apache license to src files.
https://github.com/juanmf/Java2PlantUML/commit/b17bc78dd86da8ab7a79b42356a6ce15f964b107
